### ISSUE TITLE
strange error when building cdep sample: CMAKE_SYSTEM_VERSION is 1

### ISSUE THREAD

**Issue by ggfan** [google/cdep#60]
after update cdep example to Android 3.0, it complains about CMAKE_SYSTEM_VERSION, not remember seeing before.  what I am doing is setting it to 23 ( the library supported version ) right before calling 
- find_package(cdep-dependencies REQUIRED)

and it is fine, is it correct to reset it?
  https://github.com/googlesamples/android-ndk/blob/master/hello-cdep/app/src/main/cpp/CMakeLists.txt

To reproduce the error, just remove the CMAKE_SYSTEM_VERSION inside the above mentioned CMakeLists.txt file

and you should see the  error message of:
    Android API level 1 is not supported by com.github.ggfan:hello-cdep:1.0.0

details messages:

 Call Stack (most recent call first):
  /Users/gfan/dev/android-sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt
-- Check for working C compiler: /Users/gfan/dev/sdk_current/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/gfan/dev/sdk_current/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/gfan/dev/sdk_current/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: /Users/gfan/dev/sdk_current/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /Users/gfan/proj/android-ndk/hello-cdep/.cdep/modules/cdep-dependencies-config.cmake:72 (message):
  Android API level 1 is not supported by com.github.ggfan:hello-cdep:1.0.0
Call Stack (most recent call first):
  /Users/gfan/proj/android-ndk/hello-cdep/.cdep/modules/cdep-dependencies-config.cmake:80 (add_cdep_hello_cdep_dependency)
  CMakeLists.txt:36 (add_all_cdep_dependencies)
-- Configuring incomplete, errors occurred!
See also "/Users/gfan/proj/android-ndk/hello-cdep/app/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeOutput.log".

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> executing external native build for cmake /Users/gfan/proj/android-ndk/hello-cdep/app/src/main/cpp/CMakeLists.txt

**Comment by gpx1000** [comment]
Hi from the peanut gallery.

The problem comes from this: android.toolchain.cmake line 42
# Inhibit all of CMake's own NDK handling code.
set(CMAKE_SYSTEM_VERSION 1)

When using the toolchain that is shipped with the ndk there's a specific check for CMAKE_SYSTEM_VERSION greater than 22 at line 46 of the generated cdep-dependencies-config.cmake
  if(CMAKE_SYSTEM_NAME STREQUAL "Android")
    if(CMAKE_SYSTEM_VERSION GREATER 22)
      <snip>...</snip>
    else()
        message (FATAL_ERROR "") <-- that's the failure you're seeing.

If you use a system cmake or one that doesn't use android.toolchain.cmake then the CMAKE_SYSTEM_VERSION will be set correctly and there's no need for the workaround you're deleting here.

CMAKE_SYSTEM_VERSION is a correct check to ensure that the platform OS being targeted is at a specific platform.  It is populated by buildSystemTargetPlatform.  I'd venture this is a working as designed bug.
The only real suggestion I'd have is to place a new variable in android.toolchain.cmake that doesn't conflict with CMAKE_SYSTEM_VERSION and cdep can check both?  This would eliminate the need for the workaround and mask the issue to users.

**Comment by ggfan** [comment]
yeah, that sounds correct.  thank you!
